### PR TITLE
feat: sessionStorage for burner wallet

### PR DESCRIPTION
**Pull request by rin-st**
Context: https://github.com/scaffold-eth/se-2-challenges/pull/250#issuecomment-2546275096

Also, to make it work we need to add the possibility to export it to `services/web3/wagmiConnectors.tsx`. So we need to templatize that file

Do you have any thoughts on how to make it another way?

@technophile-04

### CODE REVIEW

**Review by technophile-04 — COMMENTED** [review]
Thanks @rin-st! Just pushed https://github.com/scaffold-eth/burner-connector/pull/24/commits/b9b4f6b860e3463bbf341687eca2700718ef39a3

I think people should be able to use either one of them not both at same time (`rainbowkitBurnerConnector` | `rainbowkitSessionStorageBurnerWallet`). But since we are exposing both people can use both at same time and that can cause issue. 

So just updated it to hvae similar API to how  rianbowkit coinbase wallet has: 

Screenshot 2024-12-18 at 6 52 30 PM

So similar to this in our case people would consume sessionStorage in this way: 

```ts
import { rainbowkitBurnerWallet } from "burner-connector";

rainbowkitBurnerWallet.useSessionStorage = true 

const wallets = [metaMaskWallet, rainbowkitBurnerWallet];
```

**Review by technophile-04 — APPROVED** [review]
Could u just give it a last pair of eyes / thoughts on last commit 🙌. Happy to merge without last commit but I think it makes more sense to have the API like this but not too strong opinion.

**Comment by rin-st** [comment]
Yes I agree, thank you! 

Added small fix for default value and network

**Comment by technophile-04** [comment]
Thanks @rin-st! Merging this 🙌

**Pull request merged**
